spring:
  profiles:
    active: dev
    include:
      - base-addi
  batch:
    job:
      names: ${JOB_NAME:none}
      month:
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.starttls.enable: true
  custom:
    toss-payments:
      secret-key: ${TOSS_SECRET_KEY}
    jwt:
      secret-key: ${JWT_SECRET_KEY}
logging:
  level:
    root: info
    com.ll.exam.com.ll.exam.Week_Mission: debug
    org.hibernate.type.descriptor.sql: trace
custom:
  order:
    cancelAvailableSeconds: 600
  rebate:
    wholesalePriceRate: 0.5
  site:
    name: MEOTBOOKS
    baseUrl: "http://localhost:8010"
