spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/ebook_market__prod?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create #TODO: 최초 배포 이후 none 이나 validate 으로 수정 필요
logging:
  level:
    root: info
