spring:
  datasource:
    url: jdbc:mysql://${TEST_DB_HOST:127.0.0.1}:3306/ebook_market__test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create