spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/ebook_market__prod?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: info
